### ISSUE TITLE
Ability to append hostnames when generating certificates

### ISSUE THREAD

**Issue by bhegazy** [gruntwork-io/kubergrunt#67]
Something like 

```golang
template.DNSNames = append(template.DNSNames, hosts)
```
to [cert_common.go](https://github.com/gruntwork-io/kubergrunt/blob/master/tls/cert_common.go#L96)

Thanks

**Comment by yorinasub17** [comment]
This would be a good feature to have! A bit buried right now so won't be able to implement, but happy to review a PR if you are up for it.

**Comment by bhegazy** [comment]
I will try and put a PR up for you

**Comment by KyleMartin901** [comment]
Hi,

I had actually had already created this feature but hadn't had time to clean it up and push it till now. I required it so the FluxCD Helm Operator could talk to Tiller as it requires to talk to Tiller via its service rather than port forwarding like the Helm client does.

I originally used `append(template.DNSNames, hosts)` but felt it was probably better to add it to the x509.Certificate template rather than appending but happy to change that back if prefer it to be appended.
